/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ups.edu.ec.vista;

import java.lang.reflect.Constructor;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.JOptionPane;
import ups.edu.ec.controlador.ControladorAdministrador;
import ups.edu.ec.controlador.ControladorCasa;
import ups.edu.ec.controlador.ControladorHipoteca;
import ups.edu.ec.controlador.ControladorPersona;
import ups.edu.ec.modelo.Administrador;

/**
 *
 * @author User
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private String keyUnlock;
    private boolean inicioSesion;
    private Administrador administrador;

    private ControladorAdministrador controladorAdministrador;
    private ControladorPersona controladorPersona;
    private ControladorCasa controladorCasa;
    private ControladorHipoteca controladorHipoteca;

    private VentanaCrearAdministrador ventanaCrearAdministrador;
    private VentanaLogIn ventanaLogIn;
    private VentanaCrearPersona ventanaCrearPersona;
    private VentanaCrearCasa ventanaCrearCasa;
    private VentanaCrearHipoteca ventanaCrearHipoteca;
    private VentanaMostrarPagos ventanaMostrarPagos;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        keyUnlock = "programacion";
        inicioSesion = false;

        /*
        try {
            Constructor<Administrador> constructor;
            constructor = Administrador.class.getDeclaredConstructor();
            constructor.setAccessible(true);
            administrador = constructor.newInstance();
            administrador.setNombre("Jose");
            administrador.setApellido("Jose");
            administrador.setCedula("010101010-1");
            administrador.setCorreo("jose@gmail.com");
            administrador.setNumeroTelefono("012-345-6789");
        } catch (Exception e) {
            e.printStackTrace();
        }*/
        controladorAdministrador = new ControladorAdministrador();
        controladorPersona = new ControladorPersona();
        controladorCasa = new ControladorCasa();
        controladorHipoteca = new ControladorHipoteca();

        /* System.out.println(controladorHipoteca.calcularCargaFinaciera(new BigDecimal(120000), new BigDecimal(11.23), 16));
        System.out.println(controladorHipoteca.calcularFechaFin(new Date(121, 0, 29), 16));*/
 /*String passwordEncriptado = controladorAdministrador.encriptarPassword(keyUnlock, "1234");
        administrador.setPassword(passwordEncriptado);
        controladorAdministrador.create(administrador);*/
        ventanaMostrarPagos = new VentanaMostrarPagos();
        ventanaCrearAdministrador = new VentanaCrearAdministrador(controladorAdministrador, keyUnlock);
        ventanaLogIn = new VentanaLogIn(controladorAdministrador, keyUnlock);
        ventanaCrearPersona = new VentanaCrearPersona(controladorPersona);
        ventanaCrearCasa = new VentanaCrearCasa(controladorCasa);
        ventanaCrearHipoteca = new VentanaCrearHipoteca(controladorHipoteca, controladorPersona,
                controladorCasa, ventanaMostrarPagos);

        desktopPane.add(ventanaLogIn);
        desktopPane.add(ventanaCrearAdministrador);
        desktopPane.add(ventanaCrearPersona);
        desktopPane.add(ventanaCrearCasa);
        desktopPane.add(ventanaCrearHipoteca);
        desktopPane.add(ventanaMostrarPagos);

    }

    public void cerrarVentanas() {
        ventanaLogIn.hide();
        ventanaCrearAdministrador.hide();
        ventanaCrearPersona.hide();
        ventanaCrearCasa.hide();
        ventanaCrearHipoteca.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuIniciarSesion = new javax.swing.JMenuItem();
        cerrarSesionMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        adminMenuItem = new javax.swing.JMenuItem();
        personaMenuItem = new javax.swing.JMenuItem();
        casaMenuItem = new javax.swing.JMenuItem();
        hipotecaMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prueba");

        fileMenu.setMnemonic('f');
        fileMenu.setText("Home");

        openMenuIniciarSesion.setMnemonic('o');
        openMenuIniciarSesion.setText("Iniciar Sesion");
        openMenuIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuIniciarSesionActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuIniciarSesion);

        cerrarSesionMenuItem.setText("Cerrar Sesion");
        cerrarSesionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(cerrarSesionMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Crear");

        adminMenuItem.setMnemonic('t');
        adminMenuItem.setText("Administrador");
        adminMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(adminMenuItem);

        personaMenuItem.setMnemonic('y');
        personaMenuItem.setText("Persona");
        personaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personaMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(personaMenuItem);

        casaMenuItem.setText("Casa");
        casaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casaMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(casaMenuItem);

        hipotecaMenuItem.setMnemonic('p');
        hipotecaMenuItem.setText("Hipoteca");
        hipotecaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hipotecaMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(hipotecaMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuIniciarSesionActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        if (Administrador.instance == null) {
            ventanaLogIn.setVisible(true);
            inicioSesion = true;
        } else {
            JOptionPane.showMessageDialog(this, "Ya existe un usuario que inicio sesión", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_openMenuIniciarSesionActionPerformed

    private void cerrarSesionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionMenuItemActionPerformed
        // TODO add your handling code here:

        cerrarVentanas();
        if (inicioSesion) {
            Administrador.instance = null;
            cerrarVentanas();
            JOptionPane.showMessageDialog(this, "Sesión cerrada", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            inicioSesion = false;
        } else {
            JOptionPane.showMessageDialog(this, "Nadie ha iniciado sesión", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_cerrarSesionMenuItemActionPerformed

    private void adminMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminMenuItemActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        //ventanaCrearAdministrador.setVisible(true);

        if (Administrador.instance != null) {
            cerrarVentanas();
            ventanaCrearAdministrador.setVisible(true);
        } else {
            cerrarVentanas();
            JOptionPane.showMessageDialog(this, "Nadie ha iniciado sesión", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_adminMenuItemActionPerformed

    private void personaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personaMenuItemActionPerformed
        // TODO add your handling code here:

        cerrarVentanas();
        //ventanaCrearPersona.setVisible(true);

        if (Administrador.instance != null) {
            cerrarVentanas();
            ventanaCrearPersona.setVisible(true);

        } else {
            cerrarVentanas();
            JOptionPane.showMessageDialog(this, "Nadie ha iniciado sesión", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_personaMenuItemActionPerformed

    private void casaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casaMenuItemActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        //ventanaCrearCasa.setVisible(true);

        if (Administrador.instance != null) {
            cerrarVentanas();
            ventanaCrearCasa.setVisible(true);

        } else {
            cerrarVentanas();
            JOptionPane.showMessageDialog(this, "Nadie ha iniciado sesión", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_casaMenuItemActionPerformed

    private void hipotecaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hipotecaMenuItemActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        //ventanaCrearHipoteca.setVisible(true);

        if (Administrador.instance != null) {
            cerrarVentanas();
            ventanaCrearHipoteca.setVisible(true);

        } else {
            cerrarVentanas();
            JOptionPane.showMessageDialog(this, "Nadie ha iniciado sesión", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_hipotecaMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adminMenuItem;
    private javax.swing.JMenuItem casaMenuItem;
    private javax.swing.JMenuItem cerrarSesionMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem hipotecaMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuIniciarSesion;
    private javax.swing.JMenuItem personaMenuItem;
    // End of variables declaration//GEN-END:variables

}
