/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ups.edu.ec.vista;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class VentanaMostrarPagos extends javax.swing.JInternalFrame {

    private int plazos;
    private BigDecimal mensualidad;
    private BigDecimal total;
    private Date fechaInicio;

    /**
     * Creates new form VentanaMostrarPagos
     */
    public VentanaMostrarPagos() {
        initComponents();
    }

    public int getPlazos() {
        return plazos;
    }

    public void setPlazos(int plazos) {
        this.plazos = plazos;
    }

    public BigDecimal getMensualidad() {
        return mensualidad;
    }

    public void setMensualidad(BigDecimal mensualidad) {
        this.mensualidad = mensualidad;
    }

    public Date getFechaInicio() {
        return fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public BigDecimal getTotal() {
        return total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public void llenarTblPagos() {

        DefaultTableModel modelo = (DefaultTableModel) tblPagos.getModel();
        modelo.setRowCount(0);

        int mes = fechaInicio.getMonth();
        int anio = fechaInicio.getYear() + 1900;
        int dia = fechaInicio.getDate();
        boolean primerMes = false;
        BigDecimal sobrantePago = total;

        for (int i = 1; i <= (plazos + 1); i++) {
            if (mes > 11) {
                anio += 1;
                mes = 0;
            }

            if (!primerMes) {

                Date fecha = new Date(anio, mes, dia);
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                String fechaTexto = formatter.format(fecha);

                Object[] row = {fechaTexto, 0 + "", total.toString()
                };

                mes++;
                primerMes = true;
                modelo.addRow(row);
            } else {

                sobrantePago = BigDecimal.valueOf(sobrantePago.doubleValue() - mensualidad.doubleValue()).setScale(2, RoundingMode.CEILING);
                Date fecha = new Date(anio, mes, dia);
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                String fechaTexto = formatter.format(fecha);

                if (i != (plazos + 1)) {
                    Object[] row = {fechaTexto, mensualidad.toString(), sobrantePago.toString()
                    };

                    modelo.addRow(row);

                } else {

                    mensualidad = BigDecimal.valueOf(mensualidad.doubleValue() + sobrantePago.doubleValue());
                    sobrantePago = BigDecimal.valueOf(sobrantePago.doubleValue() - sobrantePago.doubleValue()).setScale(2, RoundingMode.CEILING);
                    Object[] row = {fechaTexto, mensualidad.toString(), sobrantePago.toString()
                    };
                    modelo.addRow(row);
                }
                mes++;

            }

        }

        tblPagos.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tblPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Mensualidad", "Valor restante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPagos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        llenarTblPagos();

    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:

        llenarTblPagos();

    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPagos;
    // End of variables declaration//GEN-END:variables
}
