/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ups.edu.ec.vista;

import ups.edu.ec.controlador.ControladorApuesta;
import ups.edu.ec.controlador.ControladorCasino;
import ups.edu.ec.controlador.ControladorCliente;

/**
 *
 * @author User
 */
public class VentanaGeneral extends javax.swing.JFrame {

    private ControladorCliente controladorCliente;
    private ControladorCasino controladorCasino;
    private ControladorApuesta controladorApuesta;

    private VentanaJuego ventanaJuego;
    private VentanaJugadores ventanaJugadores;
    private VentanaGestionApuestas ventanaGestionApuestas;

    /**
     * Creates new form VentanaGeneral
     */
    public VentanaGeneral() {
        initComponents();

        controladorCliente = new ControladorCliente();
        controladorCasino = new ControladorCasino();
        controladorApuesta = new ControladorApuesta();

        ventanaJuego = new VentanaJuego(controladorCliente, controladorCasino, controladorApuesta);
        ventanaJugadores = new VentanaJugadores(controladorCliente, controladorApuesta, controladorCasino);
        ventanaGestionApuestas = new VentanaGestionApuestas(controladorCliente, controladorApuesta);

        desktopPane.add(ventanaJuego);
        desktopPane.add(ventanaJugadores);
        desktopPane.add(ventanaGestionApuestas);

    }

    public void cerrarVentanas() {
        ventanaJuego.hide();
        ventanaJugadores.hide();
        ventanaGestionApuestas.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        juegoMenuItem = new javax.swing.JMenuItem();
        jugadoresMenuItem = new javax.swing.JMenuItem();
        apuestasMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ups/edu/ec/imagenes/ruletaPortada.jpg"))); // NOI18N
        desktopPane.add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 510);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        juegoMenuItem.setMnemonic('o');
        juegoMenuItem.setText("Juego");
        juegoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(juegoMenuItem);

        jugadoresMenuItem.setMnemonic('s');
        jugadoresMenuItem.setText("Jugadores");
        jugadoresMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadoresMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(jugadoresMenuItem);

        apuestasMenuItem.setMnemonic('a');
        apuestasMenuItem.setText("Apuestas");
        apuestasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apuestasMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(apuestasMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void juegoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoMenuItemActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        ventanaJuego.setVisible(true);

    }//GEN-LAST:event_juegoMenuItemActionPerformed

    private void jugadoresMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadoresMenuItemActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        ventanaJugadores.setVisible(true);

    }//GEN-LAST:event_jugadoresMenuItemActionPerformed

    private void apuestasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apuestasMenuItemActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        ventanaGestionApuestas.setVisible(true);
        
    }//GEN-LAST:event_apuestasMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem apuestasMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem juegoMenuItem;
    private javax.swing.JMenuItem jugadoresMenuItem;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
