/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ups.edu.ec.vista;

import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ups.edu.ec.controlador.ControladorFactura;
import ups.edu.ec.controlador.ControladorSitio;
import ups.edu.ec.modelo.Factura;

/**
 *
 * @author User
 */
public class VentanaSalidaTicket extends javax.swing.JInternalFrame {

    private Factura factura;

    private ControladorFactura controladorFactura;
    private ControladorSitio controladorSitio;

    private VentanaVisualizarFactura ventanaVisualizarFactura;
    /**
     * Creates new form VentanaSalidaTicket
     *
     * @param controladorFactura
     * @param controladorSitio
     */
    public VentanaSalidaTicket(ControladorFactura controladorFactura, ControladorSitio controladorSitio,
            VentanaVisualizarFactura ventanaVisualizarFactura) {
        initComponents();

        this.controladorFactura = controladorFactura;
        this.controladorSitio = controladorSitio;
        this.ventanaVisualizarFactura = ventanaVisualizarFactura;

        factura = new Factura();
    }

    public void cargarFecha() {
        try {
            Date fecha = new Date(Calendar.getInstance().getTimeInMillis());
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss");

            String fechaTexto = formatter.format(fecha);

            txtFechaSalida.setText(fechaTexto);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void limpiar() {
        txtCodigoBuscar.setText("");
        txtCodigoBuscar.setEditable(true);

        txtFechaEntrada.setText("");
        txtNumeroSitio.setText("");
        txtSubtotal.setText("");
        txtTotal.setText("");
        txtFormattedCedula.setValue("");
        btnGroupDescuento.clearSelection();
        txtTiempo.setText("");
        btnCrear.setEnabled(false);
        cargarFecha();

    }

    public void cargarSubtotal() {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss");
        Date fechaSalida = null;
        try {
            fechaSalida = formatter.parse(txtFechaSalida.getText());
        } catch (ParseException ex) {
            Logger.getLogger(VentanaSalidaTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
        BigDecimal subtotal = controladorFactura.calcularSubtotal(factura.getFechaEntrada(), fechaSalida);
        txtSubtotal.setText(String.valueOf(subtotal));
    }

    public void cargarTiempo() {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss");
        Date fechaSalida = null;
        try {
            fechaSalida = formatter.parse(txtFechaSalida.getText());
        } catch (ParseException ex) {
            Logger.getLogger(VentanaSalidaTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTiempo.setText(String.valueOf(controladorFactura.calcularTiempo(factura.getFechaEntrada(), fechaSalida)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDescuento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoBuscar = new javax.swing.JTextField();
        txtFechaEntrada = new javax.swing.JTextField();
        txtNumeroSitio = new javax.swing.JTextField();
        txtFormattedCedula = new javax.swing.JFormattedTextField();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFechaSalida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        radioBtnAplicar = new javax.swing.JRadioButton();
        radioBtnNoAplicar = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Factura");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Código:");

        jLabel2.setText("Fecha entrada:");

        jLabel3.setText("Código sitio asignado:");

        jLabel4.setText("Cédula cliente:");

        txtCodigoBuscar.setBackground(new java.awt.Color(255, 255, 255));

        txtFechaEntrada.setEditable(false);
        txtFechaEntrada.setBackground(new java.awt.Color(102, 102, 102));

        txtNumeroSitio.setEditable(false);
        txtNumeroSitio.setBackground(new java.awt.Color(102, 102, 102));

        txtFormattedCedula.setEditable(false);
        try {
            txtFormattedCedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnCrear.setBackground(new java.awt.Color(51, 51, 255));
        btnCrear.setText("Emitir Factura");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha salida:");

        txtFechaSalida.setEditable(false);
        txtFechaSalida.setBackground(new java.awt.Color(102, 102, 102));

        jLabel6.setText("Subtotal:");

        txtSubtotal.setEditable(false);
        txtSubtotal.setBackground(new java.awt.Color(102, 102, 102));

        btnBuscar.setBackground(new java.awt.Color(0, 0, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGroupDescuento.add(radioBtnAplicar);
        radioBtnAplicar.setText("SI");
        radioBtnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnAplicarActionPerformed(evt);
            }
        });

        btnGroupDescuento.add(radioBtnNoAplicar);
        radioBtnNoAplicar.setText("NO");
        radioBtnNoAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnNoAplicarActionPerformed(evt);
            }
        });

        jLabel8.setText("Descuento:");

        jLabel9.setText("Total:");

        txtTotal.setEditable(false);

        jLabel7.setText("$");

        jLabel10.setText("$");

        jLabel11.setText("Tiempo(minutos):");

        txtTiempo.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigoBuscar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal))
                    .addComponent(txtFormattedCedula)
                    .addComponent(txtFechaSalida)
                    .addComponent(txtFechaEntrada)
                    .addComponent(txtNumeroSitio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioBtnAplicar)
                                .addGap(24, 24, 24)
                                .addComponent(radioBtnNoAplicar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnCancelar)))
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubtotal))
                    .addComponent(txtTiempo))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroSitio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFormattedCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnAplicar)
                    .addComponent(radioBtnNoAplicar)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnCancelar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtnNoAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnNoAplicarActionPerformed
        // TODO add your handling code here:

        factura.setDescuento(false);
        txtTotal.setText(txtSubtotal.getText());
    }//GEN-LAST:event_radioBtnNoAplicarActionPerformed

    private void radioBtnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnAplicarActionPerformed
        // TODO add your handling code here:
        BigDecimal total = controladorFactura.calcularTotal(Double.valueOf(txtSubtotal.getText()), true);
        factura.setDescuento(true);
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_radioBtnAplicarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        int codigo = Integer.valueOf(txtCodigoBuscar.getText());
        //factura.setCodigo(codigo);

        factura = (Factura) controladorFactura.read(codigo);

        if (factura != null && factura.getFechaSalida() == null) {
            txtCodigoBuscar.setEditable(false);
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss");
            Date d = factura.getFechaEntrada();
            String fechaEntrada;
            fechaEntrada = formatter.format(d);
            System.out.println(fechaEntrada);
            txtFechaEntrada.setText(fechaEntrada);
            cargarFecha();
            if (factura.getCedulaClienteFk() != null) {
                txtFormattedCedula.setValue(factura.getCedulaClienteFk().getCedula());
            } else {
                txtFormattedCedula.setValue("");
            }

            txtNumeroSitio.setText(String.valueOf(factura.getNumeroSitioFk().getCodigo()));
            btnCrear.setEnabled(true);
            cargarSubtotal();
            cargarTiempo();
        } else {
            JOptionPane.showMessageDialog(this, "Factura no encontrada", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss");
        Date fechaSalida = new Date();
        try {
            fechaSalida = formatter.parse(txtFechaSalida.getText());
        } catch (ParseException ex) {

        }
        System.out.println("");
        factura.setFechaSalida(fechaSalida);
        factura.setSubtotal(BigDecimal.valueOf(Double.valueOf(txtSubtotal.getText())));
        factura.setTiempo(Integer.valueOf(txtTiempo.getText()));
        factura.setTotal(BigDecimal.valueOf(Double.valueOf(txtTotal.getText())));

        if (controladorFactura.update(factura)) {
            System.out.println(factura.getFechaEntrada() + " " + factura.getFechaSalida());
            JOptionPane.showMessageDialog(this, "Factura emitida con exito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            controladorSitio.cambiarAEstadoDesocupado(factura.getNumeroSitioFk());
            limpiar();
            ventanaVisualizarFactura.cargarFactura(factura);
            ventanaVisualizarFactura.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCrearActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        limpiar();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.ButtonGroup btnGroupDescuento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioBtnAplicar;
    private javax.swing.JRadioButton radioBtnNoAplicar;
    private javax.swing.JTextField txtCodigoBuscar;
    private javax.swing.JTextField txtFechaEntrada;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JFormattedTextField txtFormattedCedula;
    private javax.swing.JTextField txtNumeroSitio;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTiempo;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
