/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ups.edu.ec.vista;

import javax.persistence.EntityManagerFactory;
import ups.edu.ec.controlador.AsuntoJpaController;
import ups.edu.ec.controlador.ClienteJpaController;
import ups.edu.ec.controlador.ProcuradorJpaController;
import ups.edu.ec.modelo.Procurador;

/**
 *
 * @author User
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private AsuntoJpaController controladorAsunto;
    private ClienteJpaController controladorCliente;
    private ProcuradorJpaController controladorProcurador;

    private VentanaAsunto ventanaAsunto;
    private VentanaCliente ventanaCliente;
    private VentanaProcurador ventanaProcurador;
    private VentanaVista ventanaVista;

    private EntityManagerFactory emf;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

        controladorAsunto = new AsuntoJpaController();
        controladorCliente = new ClienteJpaController();
        controladorProcurador = new ProcuradorJpaController();

        ventanaAsunto = new VentanaAsunto(controladorAsunto, controladorCliente, controladorProcurador);
        ventanaCliente = new VentanaCliente(controladorCliente, controladorProcurador);
        ventanaProcurador = new VentanaProcurador(controladorProcurador, controladorAsunto);
        ventanaVista = new VentanaVista(controladorProcurador);

        ventanaCliente.setVentanaAsunto(ventanaAsunto);
        ventanaAsunto.setVentanaProcurador(ventanaProcurador);

        desktopPane.add(ventanaCliente);
        desktopPane.add(ventanaAsunto);
        desktopPane.add(ventanaProcurador);
        desktopPane.add(ventanaVista);

    }

    public void cerrarVentanas() {
        ventanaAsunto.hide();
        ventanaCliente.hide();
        ventanaProcurador.hide();
        ventanaVista.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        asuntoMenuItem = new javax.swing.JMenuItem();
        clienteMenuItem = new javax.swing.JMenuItem();
        procuradorMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        gestionProcuradorMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        vistaExpedietnesMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expediente");

        fileMenu.setMnemonic('f');
        fileMenu.setText("Crear");

        asuntoMenuItem.setMnemonic('o');
        asuntoMenuItem.setText("Asunto");
        asuntoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asuntoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(asuntoMenuItem);

        clienteMenuItem.setMnemonic('s');
        clienteMenuItem.setText("Cliente");
        clienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(clienteMenuItem);

        procuradorMenuItem.setMnemonic('a');
        procuradorMenuItem.setText("Procurador");
        procuradorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procuradorMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(procuradorMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Gestion");

        gestionProcuradorMenuItem.setMnemonic('p');
        gestionProcuradorMenuItem.setText("Procurador");
        editMenu.add(gestionProcuradorMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Vista");

        vistaExpedietnesMenuItem.setMnemonic('c');
        vistaExpedietnesMenuItem.setText("Expedientes");
        vistaExpedietnesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vistaExpedietnesMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(vistaExpedietnesMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void asuntoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asuntoMenuItemActionPerformed
        // TODO add your handling code here:

        cerrarVentanas();
        ventanaAsunto.setVisible(true);

    }//GEN-LAST:event_asuntoMenuItemActionPerformed

    private void clienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteMenuItemActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        ventanaCliente.setVisible(true);
    }//GEN-LAST:event_clienteMenuItemActionPerformed

    private void procuradorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procuradorMenuItemActionPerformed
        // TODO add your handling code here:

        cerrarVentanas();
        ventanaProcurador.setVisible(true);
    }//GEN-LAST:event_procuradorMenuItemActionPerformed

    private void vistaExpedietnesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vistaExpedietnesMenuItemActionPerformed
        // TODO add your handling code here:

        cerrarVentanas();
        ventanaVista.setVisible(true);

    }//GEN-LAST:event_vistaExpedietnesMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem asuntoMenuItem;
    private javax.swing.JMenuItem clienteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem gestionProcuradorMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem procuradorMenuItem;
    private javax.swing.JMenuItem vistaExpedietnesMenuItem;
    // End of variables declaration//GEN-END:variables

}
